# .pre-commit-config.yaml
repos:
  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=5000']
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: debug-statements
      - id: mixed-line-ending

  # Ruff - linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix, --config=pyproject.toml]
        exclude: |
            (?x)^(
              dev/|
              .*/notebooks/|
              .*\.ipynb$
            )
      # Run the formatter
      - id: ruff-format
        args: [--config=pyproject.toml]
        exclude: |
            (?x)^(
              dev/|
              .*/notebooks/|
              .*\.ipynb$
            )
  # Type checking with mypy (optional but recommended)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies:
          - types-PyYAML
          - types-tqdm
        args: [--ignore-missing-imports, --scripts-are-modules]
        exclude: ^(tests/|experiments/|__examples/|dev)

  # local -- run tests
  - repo: local
    hooks:
      - id: pytest-check
        name: Run pytest
        entry: make test
        language: system
        pass_filenames: false
        always_run: true
