params_grid:
  all:
    # feature_dim: [256, 512, 1024, 2048, 4096]
    feature_dim: [256, 512]
    heads: [2, 4, 8]
kernel_related_kwargs:
  all:
    graph_reordering_partition_size: [128, 512, 1024, 2048, 4096, 8192, 16000, 65535]
datasets:
  base_path: configs/datasets
  dirs:
    graphland_remaining:
      all: true
    main:
      all: true
    secondary:
      all: false
      choices:
        - cora
        - citeseer
        - pubmed
