precisions: ["fp32", "bf16"]
params_grid:
  all:
    # feature_dim: [256, 512, 1024, 2048, 4096]
    feature_dim: [256, 512]
    heads: [2, 4, 8]
kernel_related_kwargs:
  cuda:
    huge_degree_threshold_quantile: [0.99, 0.999, -1]
  all:
    graph_reordering_partition_size: [-1]
datasets:
  base_path: configs/datasets
  dirs:
    graphland_remaining:
      all: true
    main:
      all: true
    secondary:
      all: false
      choices:
        - cora
        - citeseer
        - pubmed
