params_grid:
  all:
    # feature_dim: [256, 512, 1024, 2048, 4096]
    feature_dim: [512]
    heads: [2]
kernel_related_kwargs:
  all:
    graph_reordering_partition_size: [-1]
datasets:
  base_path: configs/datasets
  dirs:
    graphland_remaining:
      all: false
      choices:
        - web_fraud
        - web_topics
        - web_traffic
    # main:
    #   all: true
    # secondary:
    #   all: false
    #   choices:
    #     - cora
    #     - citeseer
    #     - pubmed
