params_grid:
  all:
    feature_dim: [64, 128, 256, 512]
  cuda:
    warps_per_block: [1, 4, 16, 32]
    edges_per_block_heavy_nodes: [32, 64, 128, 512]
kernel_related_kwargs:
  cuda:
    huge_degree_threshold_quantile: [0.99, 0.999, -1]
  all:
    graph_reordering_partition_size: [-1]
datasets:
  base_path: configs/datasets
  dirs:
    graphland_remaining:
      all: true
    main:
      all: true
    secondary:
      all: false
      choices:
        - cora
        - citeseer
        - pubmed
