params_grid:
  all:
    feature_dim: [128]
kernel_related_kwargs:
  cuda:
    huge_degree_threshold_quantile: [0.99, 0.999, -1]
  all:
    graph_reordering_partition_size: [-1]
datasets:
  base_path: configs/datasets
  dirs:
    secondary:
      all: false
      choices:
        - cora
        - citeseer
        - pubmed
